library(ggplot2)
library(reshape2)
library(RMySQL)
drv=dbDriver("MySQL")
con=dbConnect(drv,dbname='new_bug_report',user='root')
stat="select report_id,what,topic from bug_res natural join Bugzilla_topics order by what;"
tableres=dbGetQuery(con,stat)
tableres<-subset(tableres,!is.na(topic))
c<-1
tab1<-data.frame(resolution=character(),no_of_bug=integer(),topic=integer(),stringsAsFactors=FALSE)
for(y in unique(tableres$what))
{
  ctn=c(0,0,0,0,0,0,0,0,0,0)
  i<-1
  while(i<=nrow(subset(tableres,what==y)))
  {
    if(tableres[i,3]==1)
    {
      ctn[1]=ctn[1]+1      
    }
    if(tableres[i,3]==2)
    {
      ctn[2]=ctn[2]+1
    }
    if(tableres[i,3]==3)
    {
      ctn[3]=ctn[3]+1 
    }
    if(tableres[i,3]==4)
    {
      ctn[4]=ctn[4]+1  
    }
    if(tableres[i,3]==5)
    {
      ctn[5]=ctn[5]+1  
    }
    if(tableres[i,3]==6)
    {
      ctn[6]=ctn[6]+1   
    }
    if(tableres[i,3]==7)
    {
      ctn[7]=ctn[7]+1   
    }
    if(tableres[i,3]==8)
    {
      ctn[8]=ctn[8]+1   
    }
    if(tableres[i,3]==9)
    {
      ctn[9]=ctn[9]+1
    }
    if(tableres[i,3]==10)
    {
      ctn[10]=ctn[10]+1
    }
    i=i+1
  }
  j<-1
  while(j<=10)
  {
    tab1[c,1]=y
    tab1[c,2]=ctn[j]
    tab1[c,3]=j
    j<-j+1
    c<-c+1
  }  
}
p1<-ggplot(tab1,aes(x=topic,y=no_of_bug))+geom_line(aes(color=resolution))
p1+scale_x_discrete(breaks=c(1,2,3,4,5,6,7,8,9,10))+geom_text(aes(label=no_of_bug),size=3)
