library(lda)
library(ggplot2)
library(reshape2)
library(tm)
library(SnowballC)
library(RMySQL)
library(stringr)
drv=dbDriver("MySQL")
con=dbConnect(drv,dbname='bug_report',user='root')
stat="select Bugzilla_severity.report_id,Bugzilla_severity.timestamp,Bugzilla_severity.what as 'severity',Bugzilla_desc.what as 'desc' from Bugzilla_severity left join Bugzilla_desc on (Bugzilla_desc.report_id=Bugzilla_severity.report_id and Bugzilla_desc.timestamp=Bugzilla_severity.timestamp);"
table1=dbGetQuery(con,stat)
sw <- c(stopwords("english"),"na","NA","content","will")
desc<-table1["desc"]
docu=""
i<-1
while(i<=5616)
{
  temp<-desc[i,1]
  temp<-lapply(temp,tolower)
  temp<-lapply(temp,removePunctuation)
  temp<-lapply(temp,removeNumbers)
  temp<-unlist(temp)
  temp<-removeWords(temp,sw)
  temp<-strsplit(temp," ")
  temp<-lapply(temp,stemDocument)
  j<-2
  while(j<=length(temp[[1]]))
  {
    temp[[1]][1]<-paste(temp[[1]][1],temp[[1]][j])
    j<-j+1
  }
  temp<-temp[[1]][1]
  desc[i,1]<-relist(temp,desc[i,1])
  docu[[i]]<-desc[i,1]
  i<-i+1
}
Table<-table1
Table['desc']<-docu
docucorp<-subset(docu,docu!="NA")
docs<-lexicalize(docucorp)
vocab=docs$vocab
docs=docs$documents
K<-10
result<-lda.collapsed.gibbs.sampler(docs,K,vocab,800,0.15,0.01,compute.log.likelihood=TRUE)
top.words <- top.topic.words(result$topics, 20, by.score=TRUE)
i<-1
j<-1 #reassign table
k<-0  #document matrix iterator
table<-data.frame(report_id=integer(),severity1=character(),severity2=character(),topic=integer(),stringsAsFactors=FALSE)
while(i<=length(docu))
{
  if((docu[[i]]=="NA"||is.na(docu[[i]])) && i>1)
  {  table[j,1]<-Table[i,1]
     table[j,2]<-Table[i-1,3]
     table[j,3]<-Table[i,3]
     table[j,4]<-which.max(result$document_sums[,k])
     j<-j+1
  }
  if(docu[[i]]!="NA"||is.na(docu[[i]]))
  {
    k<-k+1
  }
  i<-i+1
}
i<-1
tabnor<-subset(table,severity1=="normal")
distnormal<-data.frame(trivial=integer(),minor=integer(),normal=integer(),major=integer(),critical=integer(),blocker=integer())
distnormal[1,]<-c(0,0,0,0,0,0)
while(i<=dim(tabnor)[1])
{
  if(tabnor$severity2[i]=="trivial")
  {
    distnormal[1,1]<-distnormal[1,1]+1
  }
  if(tabnor$severity2[i]=="minor")
  {
    distnormal[1,2]<-distnormal[1,2]+1
  }
  if(tabnor$severity2[i]=="normal")
  {
    distnormal[1,3]<-distnormal[1,3]+1
  }
  if(tabnor$severity2[i]=="major")
  {
    distnormal[1,4]<-distnormal[1,4]+1
  }
  if(tabnor$severity2[i]=="critical")
  {
    distnormal[1,5]<-distnormal[1,5]+1
  }
  if(tabnor$severity2[i]=="blocker")
  {
    distnormal[1,6]<-distnormal[1,6]+1
  }
  i<-i+1
}
dist<-data.frame(severity=character(),t1=integer(),t2=integer(),t3=integer(),t4=integer(),t5=integer(),t6=integer(),t7=integer(),t8=integer(),t9=integer(),t10=integer(),stringsAsFactors=FALSE)
i<-1
sev<-c("trivial","minor","normal","major","critical","blocker")
while(i<=6)
{
  dist[i,1]<-sev[i]
  dist[i,2:11]<-tabulate(subset(tabnor,severity2==sev[i])$topic, nbins = 10)
  i<-i+1
}